# Generated by Django 5.0.6 on 2024-07-08 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentitem_stock_remove_wishlistitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='othermodel',
            name='content_item',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='ContentItem',
        ),
        migrations.DeleteModel(
            name='OtherModel',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='WatchlistItem',
        ),
    ]
