# Generated by Django 5.0.6 on 2024-07-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_remove_stock_description_stock_price_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default=0.0, max_length=10),
            preserve_default=False,
        ),
    ]
